### ISSUE TITLE
Install a few useful tools?

### ISSUE THREAD

**Issue by JayH5** [praekeltfoundation/seed-stack#8]
Things like...
- `vim`
- `silversearcher-ag` or `ack`

I guess these things come down to personal preference, though. Maybe we should rather keep things as a "blank slate"?

**Comment by smn** [comment]
I'd suggest we keep it as a blank slate, the idea is that it's an app
runner for development, not a dev environment itself.
The dev environment is the host machine.

On 4 November 2015 at 13:47, Jamie Hewland notifications@github.com wrote:

> Things like...
> - vim
> - silversearcher-ag or ack
> 
> I guess these things come down to personal preference, though. Maybe we
> should rather keep things as a "blank slate"?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/praekelt/seed-stack/issues/8.

## 

Simon de Haan | Chief Engineer Praekelt Foundation

praekeltfoundation.org | praekelt.com
M: +27 (0) 76 449 3806  |  http://twitter.com/smn
